# syntax = edrevo/dockerfile-plus
#
# Copyright (c) 2018 - 2022 James E. King III
#
# Use, modification, and distribution are subject to the
# Boost Software License, Version 1.0. (See accompanying file
# LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#
# Requires DOCKER_BUILDKIT=1
#

FROM ubuntu:focal
LABEL BDDE_DISTRO="ubuntu"
LABEL BDDE_EDITION="focal"
LABEL BDDE_ARCH="x86_64"
LABEL MAINTAINER="James E. King III <jking@apache.org>"

INCLUDE+ Dockerfile.ubuntu-focal.common
